# This is a basic workflow to help you get started with Actions

name: "action TEST"

# Controls when the workflow will run
on: push
# push:
#   branch:
#     - main

env:
  GLOBAL_LEVEL: "GLOBAL ENV VALUE"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    name: "first-job"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      JOB_LEVEL_1: "JOB LEVEL VALUE 1"
      JOB_LEVEL_2: "JOB LEVEL VALUE 2"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      env:
        STEP_LEVEL_1: "STEP LEVEL VALUE 1"
        STEP_LEVEL_2: "STEP LEVEL VALUE 2"

      # Runs a single command using the runners shell
      - name: echo Hello world
        shell: bash
        run: |
          echo "Hello World from step"
          echo "GLOBAL: $env.GLOBAL_LEVEL"
          echo "JOB 1: ${{ env.JOB_LEVEL_1 }}"
          echo "STEP 1: ${{ env.STEP_LEVEL_1 }}"
          echo "JOB 2: ${{ env.JOB_LEVEL_2 }}"
          echo "STEP 2: ${{ env.STEP_LEVEL_2 }}"

      - name: echo Hello world 2
        shell: bash
        run: |
          echo "Hello World from step"
          echo "GLOBAL: $env.GLOBAL_LEVEL"
          echo "JOB 1: ${{ env.JOB_LEVEL_1 }}"
          echo "STEP 1: ${{ env.STEP_LEVEL_1 }}"
          echo "JOB 2: ${{ env.JOB_LEVEL_2 }}"
          echo "STEP 2: ${{ env.STEP_LEVEL_2 }}"

      # Runs a set of commands using the runners shell
