name: 'SWM GitHub Actions Basic'

on: push

jobs:
  build-test:
    name: 'build to test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Send a message to webex space
      shell: bash
      run: |
        curl -X POST 'https://webexapis.com/v1/messages' \
          -H 'Authorization: Baarer ${{ secrets.WEBEX_TOKEN }}' \
          -H 'Content-Type: application/json' \
          -d '{
            "roomId": "${{ secrets.WEBEX_ROOM_ID }}",
            "text" : "1123"
          }'

    - name: Post Message to Webex Room
        uses: chrivand/action-webex-js@main
        env:
          WEBEX_TOKEN: ${{ secrets.WEBEX_TOKEN }}
          WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOM_ID }}
          MARKDOWN_MESSAGE: "**Hello, world! You just ran an action from ${{ github.repository }}.**"