name: 'SWM GitHub Actions Basic'

on: push

jobs:
  build-test:
    name: 'build to test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Send a message to webex space
      shell: bash
      run: |
        curl -X POST 'https://webexapis.com/v1/messages' \
          -H 'Authorization: Bareer ${{ secrets.WEBEX_TOKEN }}' \
          -H 'Content-type: application/json' \
          -d "{
            "roomId": "${{ secrets.WEBEX_ROOM_ID }}",
            "text" : "메세지입니다."
          }"