name: 'SWM GitHub Actions Basic'

on: push

env:
  WORKFLOW_LEVEL: "This value comes from the WORKFLOW level"

jobs:
  build-test:
    name: 'build to test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash
      run: |

  deploy-dev:
    name: 'deploy to dev'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash
      run: |

  deploy-staging:
    name: 'deploy to staging'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash
      run: |

  deploy-live:
    name: 'deploy to live'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World 1
      shell: bash
      run: |