name: 'SWM GitHub Actions Basic'

on: push

env:
  WORKFLOW_LEVEL: "This value comes from the WORKFLOW level"

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    env:
      JOB_LEVEL: "This value comes from the JOB level"

    steps:
    - name: Say Hello World 1 - ${{ matrix.os }}
      shell: bash
      run: |
        echo "OS: ${{ matrix.os }}"