# This is a basic workflow to help you get started with Actions

name: "action TEST"

# Controls when the workflow will run
on: push
# push:
#   branch:
#     - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    name: "first-job"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: echo Hello world
        shell: bash
        run: echo "Hello World from step"

      - name: echo Hello world 2
        shell: bash
        run: echo "Hello World from step"

      # Runs a set of commands using the runners shell
