name: 'SWM GitHub Actions Basic'

on: 
  push:

  workflow_dispatch:

jobs:
  webex_message:
    runs-on: ubuntu-latest
    name: Send a Webex Notification
    steps:
      - name: Post Message to Webex Room
        uses: chrivand/action-webex-js@main
        env:
          WEBEX_TOKEN: ${{ secrets.WEBEX_TOKEN }}
          WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOM_ID }}
          MARKDOWN_MESSAGE: "**Hello, world! You just ran an action from ${{ github.repository }}.**"

      - name: Send a message to webex space
      shell: bash
      run: |
        curl -X POST 'https://webexapis.com/v1/messages' \
          -H 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
          -H 'Content-Type: application/json' \
          -d '{
            "roomId": "${{ secrets.WEBEX_ROOM_ID }}",
            "text" : "1123"
          }'